framework:
  website: struts.apache.org
  version: 2.5

build:
  - mvn clean package

bin_deps:
  - jetty-runner

files:
  - target/struts2-1.0.war

command: java  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts  -jar /usr/share/java/jetty-runner.jar --port 3000 target/struts2-1.0.war
